variable "Settings" {}
variable "EnvName" {}
variable "AMI" {}
variable "KeyPair" {}
variable "InstanceSecurityGroupId" {}
variable "PublicSubnetId" {}
variable "EC2InstanceProfile" {}
variable "Name" {}
variable "TargetGroup" {}
variable "UserData" {}
